//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUtilitiesCore.Data.ValidationAttributes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationAtrributesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationAtrributesStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KUtilities.DataAnnotationsEx.ValidationAttributes.ValidationAtrributesStrings", typeof(ValidationAtrributesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo encontrar la propiedad llamada {0}.
        /// </summary>
        internal static string ValidatiomPropertyNotFound {
            get {
                return ResourceManager.GetString("ValidatiomPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha seleccionada en {0} no puede ser mayor que {1}..
        /// </summary>
        internal static string ValidationGreaterThanError {
            get {
                return ResourceManager.GetString("ValidationGreaterThanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha seleccionada en {0} no puede ser mayor o igual que {1}.
        /// </summary>
        internal static string ValidationGreaterThanOrEqualToError {
            get {
                return ResourceManager.GetString("ValidationGreaterThanOrEqualToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} No es valor tipo fecha..
        /// </summary>
        internal static string ValidationIsNotDateTypeError {
            get {
                return ResourceManager.GetString("ValidationIsNotDateTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha seleccionada en {0} no puede ser menor que {1}.
        /// </summary>
        internal static string ValidationLessThanError {
            get {
                return ResourceManager.GetString("ValidationLessThanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha seleccionada en {0} no puede ser menor o igual que {1}.
        /// </summary>
        internal static string ValidationLessThanOrEqualToError {
            get {
                return ResourceManager.GetString("ValidationLessThanOrEqualToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La regla {0} esta comparando la misma propiedad..
        /// </summary>
        internal static string ValidationSamePropertyError {
            get {
                return ResourceManager.GetString("ValidationSamePropertyError", resourceCulture);
            }
        }
    }
}
