<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
<PropertyGroup>
   <LangVersion>latest</LangVersion>
   <Title>KUtilitiesCore.MVVM</Title>
   <Description>Implementaciones core para el patrón Model-View-ViewModel, incluyendo RelayCommands y asistentes para ViewModels.</Description>
   <PackageReadmeFile>README.md</PackageReadmeFile>
   <GenerateDocumentationFile>True</GenerateDocumentationFile>
 </PropertyGroup>
 <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
 </ItemGroup>
<ItemGroup>
  <Compile Remove="ActionResult\**" />
  <Compile Remove="Messaging\**" />
  <EmbeddedResource Remove="ActionResult\**" />
  <EmbeddedResource Remove="Messaging\**" />
  <None Remove="ActionResult\**" />
  <None Remove="Messaging\**" />
</ItemGroup>
<ItemGroup>
    <Compile Remove="Helpers\ExpressionsExtCore.cs" />
</ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\KUtilitiesCore\KUtilitiesCore.csproj" />
</ItemGroup>

</Project>
