name: Publish NuGet

on:
  push:
    tags:
      - 'v*' # Solo ejecuta en push de tags que empiezan con 'v'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            4.8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack non-test projects
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          for proj in $(find . -name '*.csproj' ! -path '*Test*' ! -path '*Tests*'); do
            dotnet pack "$proj" --configuration Release --output ./nupkg /p:PackageVersion=$VERSION
          done

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}